//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goldsmith_p2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customerss
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<decimal> Gold_in_grams { get; set; }
        public Nullable<decimal> Total_amount { get; set; }
        public Nullable<decimal> Advance_amount { get; set; }
        public Nullable<decimal> Balance_amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
